# coding: UTF-8
from hashlib import pbkdf2_hmac as IIIIIIIIIIIIIIIIIIII1IIIIIIIII
from binascii import unhexlify as IIIIIIIIIIII1IIIIIIIIIIIIIIIII
IIIII1IIIIIIIIIIIIIIIIIIIIIIII = (b'v')
IIIIIIIIII1IIIIIIIIIIIIIIIIIII = (b'r')
IIIIIIIIIII1IIIIIIIIIIIIIIIIII = 1
IIIIIIIIIIIII1IIIIIIIIIIIIIIII = (b'5')
IIIIIIIIIIIIIIIIIIIIIIII1IIIII = IIIIIIIIIII1IIIIIIIIIIIIIIIIII + IIIIIIIIIII1IIIIIIIIIIIIIIIIII
IIIIIIIIIIIIIIIIIIIIIIIIIIII1I = ('a')
IIIIIIIIIIIIIII1IIIIIIIIIIIIII = IIIIIIIIIIIIIIIIIIIIIIII1IIIII + IIIIIIIIIII1IIIIIIIIIIIIIIIIII
IIIIIIIIIIIIIIII1IIIIIIIIIIIII = (b't')
IIIIIIII1IIIIIIIIIIIIIIIIIIIII = IIIIIIIIIIIIIIIIIIIIIIII1IIIII + IIIIIIIIIIIIIII1IIIIIIIIIIIIII
IIIIIIIIIIIIIIIIIIIIIIIIIII1II = ('2')
III1IIIIIIIIIIIIIIIIIIIIIIIIII = IIIIIIII1IIIIIIIIIIIIIIIIIIIII + IIIIIIII1IIIIIIIIIIIIIIIIIIIII + IIIIIIIIIIIIIIIIIIIIIIII1IIIII + IIIIIIIIIII1IIIIIIIIIIIIIIIIII
IIIIIIIIIIIIIIIII1IIIIIIIIIIII = (b'z')
IIIIIIIIIIIIIIIIIII1IIIIIIIIII = ('h')
IIIIII1IIIIIIIIIIIIIIIIIIIIIII = ('5')
IIIIIIIIIIIIIIIIIIIIIIIIII1III = ('s')
IIIIIIIIIIIIIIIIIIIII1IIIIIIII = IIIIIIIIIIIIIIIIIIIIIIII1IIIII * IIIIIIIIIIIIIIIIIIIIIIII1IIIII
IIIIIIIII1IIIIIIIIIIIIIIIIIIII = ('1')
IIIIIIIIIIIIIIIIIIIIII1IIIIIII = (b'f')
def I11I1IIII1II11111II1I1I1II11I1I(IIIIIIIIIIIIIIIIIIIIIIIII1IIII): return (IIIIIIIIIIIIIIIIIIII1IIIIIIIII(IIIIIIIIIIIIIIIIIIIIIIIIII1III + (IIIIIIIIIIIIIIIIIII1IIIIIIIIII + (IIIIIIIIIIIIIIIIIIIIIIIIIIII1I + (IIIIII1IIIIIIIIIIIIIIIIIIIIIII) + (IIIIIIIII1IIIIIIIIIIIIIIIIIIII) + (IIIIIIIIIIIIIIIIIIIIIIIIIII1II))), (IIIII1IIIIIIIIIIIIIIIIIIIIIIII) + IIIIIIIIIIIIIIIIIIIIII1IIIIIII + IIIIIIIIIIIIIIII1IIIIIIIIIIIII + IIIIIIIIII1IIIIIIIIIIIIIIIIIII + IIIIIIIIIIIIIIIII1IIIIIIIIIIII + IIIIIIIIIIIII1IIIIIIIIIIIIIIII + IIIIIIIIII1IIIIIIIIIIIIIIIIIII + IIIII1IIIIIIIIIIIIIIIIIIIIIIII, (IIIIIIIIIIII1IIIIIIIIIIIIIIIII)(IIIIIIIIIIIIIIIIIIIIIIIII1IIII), ((III1IIIIIIIIIIIIIIIIIIIIIIIIII * IIIIIIIIIIIIIIIIIIIIIIII1IIIII * IIIIIIIIIIIIIII1IIIIIIIIIIIIII * IIIIIIIIIIIIIIIIIIIIIIII1IIIII) - (IIIIIIIIIIIIIIIIIIIIIIII1IIIII) + (III1IIIIIIIIIIIIIIIIIIIIIIIIII * IIIIIIII1IIIIIIIIIIIIIIIIIIIII * III1IIIIIIIIIIIIIIIIIIIIIIIIII)), (III1IIIIIIIIIIIIIIIIIIIIIIIIII) + ((IIIIIIII1IIIIIIIIIIIIIIIIIIIII + IIIIIIIIIII1IIIIIIIIIIIIIIIIII) + (IIIIIIII1IIIIIIIIIIIIIIIIIIIII * IIIIIIIIIIIIIIIIIIIIIIII1IIIII) + IIIIIIIIIIIIIII1IIIIIIIIIIIIII)))
